version: "3"
services:
  apollo-router:
    image: ghcr.io/apollographql/router:v1.25.0
    environment:
    - APOLLO_ROUTER_SUPERGRAPH_PATH=/repo/dev/apollo-federation/supergraph.graphql
    - APOLLO_ROUTER_CONFIG_PATH=/repo/dev/apollo-federation/router.yaml
    volumes:
    - ${HOST_PROJECT_PATH:-.}/dev:/repo/dev
