// source: transactions.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.services.transactions.v1.SettlementViaType', null, global);
goog.exportSymbol('proto.services.transactions.v1.SubscribeTransactionsRequest', null, global);
goog.exportSymbol('proto.services.transactions.v1.TransactionEvent', null, global);
goog.exportSymbol('proto.services.transactions.v1.TransactionType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.transactions.v1.SubscribeTransactionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.transactions.v1.SubscribeTransactionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.transactions.v1.SubscribeTransactionsRequest.displayName = 'proto.services.transactions.v1.SubscribeTransactionsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.transactions.v1.TransactionEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.transactions.v1.TransactionEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.transactions.v1.TransactionEvent.displayName = 'proto.services.transactions.v1.TransactionEvent';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.services.transactions.v1.SubscribeTransactionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.transactions.v1.SubscribeTransactionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
afterTransactionId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.transactions.v1.SubscribeTransactionsRequest}
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.transactions.v1.SubscribeTransactionsRequest;
  return proto.services.transactions.v1.SubscribeTransactionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.transactions.v1.SubscribeTransactionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.transactions.v1.SubscribeTransactionsRequest}
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAfterTransactionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.transactions.v1.SubscribeTransactionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.transactions.v1.SubscribeTransactionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string after_transaction_id = 1;
 * @return {string}
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.prototype.getAfterTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.transactions.v1.SubscribeTransactionsRequest} returns this
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.prototype.setAfterTransactionId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.transactions.v1.SubscribeTransactionsRequest} returns this
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.prototype.clearAfterTransactionId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.transactions.v1.SubscribeTransactionsRequest.prototype.hasAfterTransactionId = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.transactions.v1.TransactionEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.services.transactions.v1.TransactionEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.transactions.v1.TransactionEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.transactions.v1.TransactionEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
ledgerTransactionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
walletId: jspb.Message.getFieldWithDefault(msg, 2, ""),
accountId: jspb.Message.getFieldWithDefault(msg, 3, ""),
paymentHash: jspb.Message.getFieldWithDefault(msg, 4, ""),
satsAmount: jspb.Message.getFieldWithDefault(msg, 5, 0),
centsAmount: jspb.Message.getFieldWithDefault(msg, 6, 0),
currency: jspb.Message.getFieldWithDefault(msg, 7, ""),
type: jspb.Message.getFieldWithDefault(msg, 8, 0),
settlementVia: jspb.Message.getFieldWithDefault(msg, 9, 0),
pending: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
timestamp: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.transactions.v1.TransactionEvent}
 */
proto.services.transactions.v1.TransactionEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.transactions.v1.TransactionEvent;
  return proto.services.transactions.v1.TransactionEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.transactions.v1.TransactionEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.transactions.v1.TransactionEvent}
 */
proto.services.transactions.v1.TransactionEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLedgerTransactionId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWalletId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPaymentHash(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSatsAmount(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCentsAmount(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    case 8:
      var value = /** @type {!proto.services.transactions.v1.TransactionType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 9:
      var value = /** @type {!proto.services.transactions.v1.SettlementViaType} */ (reader.readEnum());
      msg.setSettlementVia(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPending(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.transactions.v1.TransactionEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.transactions.v1.TransactionEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.transactions.v1.TransactionEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.transactions.v1.TransactionEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerTransactionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWalletId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAccountId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPaymentHash();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSatsAmount();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getCentsAmount();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getCurrency();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getSettlementVia();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getPending();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      11,
      f
    );
  }
};


/**
 * optional string ledger_transaction_id = 1;
 * @return {string}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getLedgerTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setLedgerTransactionId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string wallet_id = 2;
 * @return {string}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getWalletId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setWalletId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string account_id = 3;
 * @return {string}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getAccountId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setAccountId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string payment_hash = 4;
 * @return {string}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getPaymentHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setPaymentHash = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 sats_amount = 5;
 * @return {number}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getSatsAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setSatsAmount = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 cents_amount = 6;
 * @return {number}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getCentsAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setCentsAmount = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string currency = 7;
 * @return {string}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setCurrency = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional TransactionType type = 8;
 * @return {!proto.services.transactions.v1.TransactionType}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getType = function() {
  return /** @type {!proto.services.transactions.v1.TransactionType} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.services.transactions.v1.TransactionType} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional SettlementViaType settlement_via = 9;
 * @return {!proto.services.transactions.v1.SettlementViaType}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getSettlementVia = function() {
  return /** @type {!proto.services.transactions.v1.SettlementViaType} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.services.transactions.v1.SettlementViaType} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setSettlementVia = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional bool pending = 10;
 * @return {boolean}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getPending = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setPending = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional uint64 timestamp = 11;
 * @return {number}
 */
proto.services.transactions.v1.TransactionEvent.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.transactions.v1.TransactionEvent} returns this
 */
proto.services.transactions.v1.TransactionEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * @enum {number}
 */
proto.services.transactions.v1.TransactionType = {
  TRANSACTION_TYPE_UNSPECIFIED: 0,
  SENT: 1,
  RECEIVED: 2
};

/**
 * @enum {number}
 */
proto.services.transactions.v1.SettlementViaType = {
  SETTLEMENT_VIA_UNSPECIFIED: 0,
  LIGHTNING: 1,
  INTRA_LEDGER: 2,
  ONCHAIN: 3
};

goog.object.extend(exports, proto.services.transactions.v1);
