mutation NwcConnectionCreate($input: NwcConnectionCreateInput!) {
  nwcConnectionCreate(input: $input) {
    errors {
      message
      code
      path
    }
    connectionUri
    connection {
      id
      alias
      appPubkey
      permissions
      revoked
      budgets {
        amountSats
        period
      }
    }
  }
}
