extend schema @link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@key", "@shareable", "@interfaceObject"])

type Query {
    hello: String!
    nwcServiceInfo: NwcServiceInfo!
}
scalar UserId
scalar AccountId
scalar WalletId
scalar Timestamp
interface Error
{
    code: String
    message: String!
    path: [String]
}
type GraphQLApplicationError implements Error @shareable
{
    code: String
    message: String!
    path: [String]
}

extend type User @key(fields: "id") {
    id: ID!
    exampleField: String
    nwcConnection(id: ID!): NwcConnection
    nwcConnections(includeRevoked: Boolean): [NwcConnection!]!
}

type Mutation {
    nwcConnectionCreate(input: NwcConnectionCreateInput!): NwcConnectionCreatePayload!
    nwcConnectionUpdate(input: NwcConnectionUpdateInput!): NwcConnectionUpdatePayload!
    nwcConnectionDelete(input: NwcConnectionDeleteInput!): NwcConnectionDeletePayload!
    nwcConnectionRevoke(input: NwcConnectionRevokeInput!): NwcConnectionRevokePayload!
    nwcConnectionRevokeAll: NwcConnectionRevokeAllPayload!
}

type NwcServiceInfo {
    supportedMethods: [Nip47Method!]!
    supportedNotifications: [NwcNotificationType!]!
    relayUrl: String!
}

type NwcConnection @key(fields: "id") {
    id: ID!

    userId: UserId!
    accountId: AccountId!
    walletId: WalletId!
    walletCurrency: WalletCurrency!

    alias: String
    appPubkey: String!
    permissions: [Nip47Method!]!
    notificationsEnabled: Boolean!

    revoked: Boolean!
    expiresAt: Timestamp
    revokedAt: Timestamp
    lastUsedAt: Timestamp

    createdAt: Timestamp!
    updatedAt: Timestamp!
}

enum WalletCurrency {
    BTC
    USD
}

enum Nip47Method {
    GET_INFO
    GET_BALANCE
    MAKE_INVOICE
    PAY_INVOICE
    LOOKUP_INVOICE
    LIST_TRANSACTIONS
}

enum NwcNotificationType {
    PAYMENT_SENT
    PAYMENT_RECEIVED
}

input NwcConnectionCreateInput {
    walletId: WalletId!
    alias: String
    apiKey: String!
    apiKeyId: String
    permissions: [Nip47Method!]!
    walletCurrency: WalletCurrency
    expiresAt: Timestamp
    notificationsEnabled: Boolean
}

input NwcConnectionUpdateInput {
    id: ID!
    alias: String
    permissions: [Nip47Method!]
    notificationsEnabled: Boolean
}

input NwcConnectionDeleteInput {
    id: ID!
}

input NwcConnectionRevokeInput {
    id: ID!
}

type NwcConnectionCreatePayload {
    errors: [Error!]!
    connection: NwcConnection
    connectionUri: String
}

type NwcConnectionUpdatePayload {
    errors: [Error!]!
    connection: NwcConnection
}

type NwcConnectionDeletePayload {
    errors: [Error!]!
    success: Boolean!
}

type NwcConnectionRevokePayload {
    errors: [Error!]!
    connection: NwcConnection
}

type NwcConnectionRevokeAllPayload {
    errors: [Error!]!
    revokedCount: Int!
}
