extend schema @link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@key", "@shareable", "@interfaceObject"])

type Query {
    hello: String!
}
scalar UserId
scalar AccountId
scalar WalletId
scalar Timestamp
interface Error
{
    code: String
    message: String!
    path: [String]
}
type GraphQLApplicationError implements Error @shareable
{
    code: String
    message: String!
    path: [String]
}

extend type User @key(fields: "id") {
    id: ID!
    exampleField: String
    nwcConnections: [NwcConnection!]!
}

type Mutation {
    nwcConnectionCreate(input: NwcConnectionCreateInput!): NwcConnectionCreatePayload!
    nwcConnectionUpdate(input: NwcConnectionUpdateInput!): NwcConnectionUpdatePayload!
    nwcConnectionDelete(input: NwcConnectionDeleteInput!): NwcConnectionDeletePayload!
}

type NwcConnection @key(fields: "id") {
    id: ID!

    userId: UserId
    accountId: AccountId!
    walletId: WalletId!

    alias: String
    appPubkey: String!
    permissions: [Nip47Method!]!
    notificationsEnabled: Boolean!

    revoked: Boolean!

    createdAt: Timestamp!
    updatedAt: Timestamp!
}

enum Nip47Method {
    GET_INFO
    GET_BALANCE
    MAKE_INVOICE
    PAY_INVOICE
    LOOKUP_INVOICE
    LIST_TRANSACTIONS
}

input NwcConnectionCreateInput {
    walletId: WalletId!
    alias: String
    apiKey: String!
    permissions: [Nip47Method!]!
}

input NwcConnectionUpdateInput {
    id: ID!
    alias: String
    permissions: [Nip47Method!]
}

input NwcConnectionDeleteInput {
    id: ID!
}

type NwcConnectionCreatePayload {
    errors: [Error!]!
    connection: NwcConnection
    connectionUri: String
}

type NwcConnectionUpdatePayload {
    errors: [Error!]!
    connection: NwcConnection
}

type NwcConnectionDeletePayload {
    errors: [Error!]!
    success: Boolean!
}