name: "Bats test"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Bats tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix develop -c pnpm install --frozen-lockfile
      - name: Run bats tests
        run: |
          . ./.envrc && nix develop -c make reset-bats
