name: "Bats test"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Bats tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix develop -c pnpm install --frozen-lockfile
      - name: Run bats tests
        run: nix develop -c ./dev/ci_run.sh
      - name: Upload Tilt log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bats-tilt-log
          path: dev/.e2e-tilt.log
